name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: prateekv19/paytm:latest

      - name: Verify Pushed Image
        run: docker pull prateekv19/paytm:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            # Pull latest Docker image
            sudo docker pull prateekv19/paytm:latest

            # Stop and remove existing container if running
            sudo docker stop web-app || true
            sudo docker rm web-app || true

            # Run Docker container with secrets passed as environment variables
            sudo docker run -d --name web-app \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              -p 3005:3000 \
              prateekv19/paytm:latest
